defaults: &defaults
  sni: true
  private_key_encoded: <%= ENV['NOTARY_PRIVATE_KEY'] %>
  observation_update_limit: <%= 60*60*48 %> # 2 days
  observation_cool_off: <%= 60*5 %> # 5 minutes

development:
  <<: *defaults
  db: 'sqlite::memory:'

production:
  <<: *defaults
  db: <%= ENV['DATABASE_URL'] %>