defaults: &defaults
  sni: true
  private_key_encoded: <%= ENV['NOTARY_PRIVATE_KEY'] %>
  observation_update_limit: <%= 60*60*48 %> # Create a new observation after 2 days
  observation_cool_off: <%= 60*30 %> # 30 minutes
  auto_reobserve_interval: <%= 60*60 %> #1 hour
  auto_reobserve_count: 5

development:
  <<: *defaults
  db: 'sqlite::memory:'

testing:
  <<: *defaults
  db: 'sqlite::memory:'

production:
  <<: *defaults
  db: <%= ENV['DATABASE_URL'] %>