defaults: &defaults
  sni: <%= ENV['NOTARY_SNI'] || true %>
  private_key_encoded: <%= ENV['NOTARY_PRIVATE_KEY'] %>
  observation_update_limit: <%= ENV['NOTARY_OBS_UPDATE_LIMIT'] || 60*60*48 %> # Create a new observation after 2 days
  observation_cool_off: <%= ENV['NOTARY_OBS_COOL_OFF'] || 60*30 %> # 30 minutes
  auto_reobserve_interval: <%= ENV['NOTARY_AUTO_REOBS_INTERVAL'] || 60*60*6 %> #6 hours
  auto_reobserve_count: <%= ENV['NOTARY_AUTO_REOBS_COUNT'] || 20 %>

development:
  <<: *defaults
  db: 'sqlite::memory:'

testing:
  <<: *defaults
  db: 'sqlite::memory:'

production:
  <<: *defaults
  db: <%= ENV['DATABASE_URL'] %>